
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: "README.md"
  - id: end-of-file-fixer
  - id: debug-statements

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
  rev: "v0.0.276"
  hooks:
  - id: ruff

- repo: https://github.com/python-poetry/poetry
  rev: "1.5.0" # add version here
  hooks:
  - id: poetry-check
  - id: poetry-export
    args: ["-f", "requirements.txt", "-o", "custom_predictor/requirements.txt", "--without-hashes", "--without", "dev"]
  - id: poetry-export
    args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes", "--with", "dev"]

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.17.0
  hooks:
  - id: gitleaks
