name: "Build and Push Docker Image"
on:
  workflow_call:
    inputs:
      DOCKER_FILEPATH:
        description: "The path dockerfile."
        required: false
        type: string
        default: custom_predictor/Dockerfile
      IMAGE_NAME:
        description: "The name of the docker image."
        required: false
        type: string
        default: kserve-demo

jobs:
  build-image:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_SECRET }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.DOCKER_FILEPATH }}
        push: true
        tags: lloydhamilton/kserve-demo:latest
        platforms: linux/amd64,linux/arm64/v8
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
