name: CI

on:
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/pytest.yaml@main
  docker-build:
    needs: unit-tests
    name: Build Docker Image
    uses: ./.github/workflows/build_push_docker.yaml@main
